"
For each assigned night shift, a medical staff should get compensation of 10% of the total working time in the night shift.
The compensation is considered over a year and not for individual night shifts.
For example, If a doctor works in three night shifts, i.e., for 27 hours in a night shifts, then she must be able to claim 2.7 hours of compensation (free time).
However, she cannot decide when to consume this compensation.
Alternatively, she can get paid for the equivalent of compensation time in salary.


"
Class {
	#name : #HMNightShiftCompensationConstraint,
	#superclass : #HMShiftConstraint,
	#category : 'Hospital-Management-Model'
}
