Class {
	#name : #ABCustomAddressBookExamples,
	#superclass : #Object,
	#traits : 'TABCreateAddressBookParametrizedExamples + TABAddContactsParametrizedExamples + TABCreateContactParametrizedExamples + TEParametrizedExamplesListExtension',
	#classTraits : 'TABCreateAddressBookParametrizedExamples classTrait + TABAddContactsParametrizedExamples classTrait + TABCreateContactParametrizedExamples classTrait + TEParametrizedExamplesListExtension classTrait',
	#category : #'AddressBook-Scenarios'
}

{ #category : #accessing }
ABCustomAddressBookExamples class >> label [
	^  'Custom Address Book'
]
